### ISSUE TITLE
This did not install the nightly.

### ISSUE THREAD

**Issue by realisation** [mjlbach/neovim-nightly-overlay#17]

**Comment by mjlbach** [comment]
I'm going to need more information to diagnose your issue. You can see exactly how I use this in my home-manager configuration here:

https://github.com/mjlbach/nix-dotfiles/blob/master/nixpkgs/overlays/nvim.nix
https://github.com/mjlbach/nix-dotfiles/blob/master/nixpkgs/modules/neovim.nix

**Comment by realisation** [comment]
Actually I see that it did now that I checked my version again.

When I checked my version after installing it last night, it still said 0.4.something. 

Now it says 0.5.0

**Comment by mjlbach** [comment]
Great! Glad it's working for you.
