### ISSUE TITLE
IDEA: Scheduled GitHub action to build for different platforms?

### ISSUE THREAD

**Issue by sayanarijit** [mjlbach/neovim-nightly-overlay#20]
It'd be a great use of GitHub actions to build binaries for Linux, Mac, (and maybe windows) and upload to cachix on a schedule. I'll check if I find a template lying around.

**Comment by mjlbach** [comment]
@sayanarijit Neovim already does this? What advantage would this offer over: https://github.com/neovim/neovim/releases/tag/nightly

**Comment by mjlbach** [comment]
@sayanarijit this repository does automatically build and distribute binary builds via cachix for macOS and linux, and it uses niv to update the hashes every night to follow master. No worries, not noise at all; just want to make sure I'm addressing your questions.
