### ISSUE TITLE
Is it possible to override?

### ISSUE THREAD

**Issue by tssm** [mjlbach/neovim-nightly-overlay#21]
I have a custom setup using the `override` attribute as outlined [here](https://nixos.wiki/wiki/Vim#Custom_setup_without_using_Home_Manager). I tried to modify it to install nightly keeping my setup, but looks like the expression doesn't accept such attribute:

```
unpacking 'https://github.com/NixOS/nixpkgs-channels/archive/6d4b93323e7f78121f8d6db6c59f3889aa1dd931.tar.gz'...
error: anonymous function at /nix/store/sc3wfhm9aa1lsrhawdbg7x8s93i4n9an-source/pkgs/applications/editors/neovim/default.nix:1:1 called with unexpected argument 'configure', at /nix/store/sc3wfhm9aa1lsrhawdbg7x8s93i4n9an-source/lib/customisation.nix:79:63
```

Would it possible to do it some how?

**Comment by mjlbach** [comment]
Can your provide a shell.nix that reproduces your issue? You should be able to perform the override on the neovim-nightly attribute.

**Comment by tssm** [comment]
Thanks for your answer @mjlbach, I'm considering migrating to home-manager, I just thought it would take me less time to install it using [my override](https://github.com/tssm/.config/blob/master/nixpkgs/overlays/neovim.nix) for the moment. I'm importing neovim-nighly in a new overlay in `nixpkgs/overlays/neovim-nightly.nix`, and I'm trying `neovim = super.neovim-nightly.override { my code }`, so `nix-env -i neovim` would install nightly, but it fails with the error before. Maybe what I'm trying is too dirty to work anyway
