### ISSUE TITLE
How do I use it with flakes?

### ISSUE THREAD

**Issue by Kazimazi** [mjlbach/neovim-nightly-overlay#49]
Just can't figure it out.:(

**Comment by mjlbach** [comment]
You should be able to use overlays without using flakes, so this can coexist with your flakified setup. I'm not planning on explicitly having this versioned via flakes until it hits nix stable, at which point I will also remove niv.

**Comment by mjlbach** [comment]
I added instructions for using the repo as a flake. I have restructured the repo to primarily version itself using flakes.
